pub(crate) fn text() -> &'static str {
    concat!(
        "usage: ultragoal --root <root> source audit --receipt <path>",
        " | package digest",
        " | install audit --receipt <path> [--installed-root <path>]",
        " | cache audit --receipt <path> [--cache-root <path>]",
        " | review-target build --receipt <path>",
        " | archive build --zip <path> --receipt <path>",
        " | review-round verify --receipt <path> --validator-receipt <path>",
        " --review-target-receipt <path> --archive-receipt <path>",
        " | final-packet prove --receipt <path>",
        " | product prove-fitness --receipt-dir <dir>",
        " | standards-gardener rebind --receipt <path>",
        " | session-log hardening rebind --receipt <path>",
        " | transaction finalize --receipt <path>",
        " | rust <toolchain verify|fast|standard|release|clean-proof|watch|",
        "memory prove|dependency audit|coverage prove --exact|workspace topology check>",
        " --receipt <path>",
        " | gc <plan|dry-run|apply|verify> --receipt <path>",
        " | halo capability prove --receipt <path>",
        " | improvement-loop prove --receipt <path>",
        " | observe <stack|logs|metrics|traces|snapshot|prove|explain-*> ...",
        " | openai config prove --receipt <path>",
        " | openai call prove --receipt <path> [--mode no_network|offline_fixture|local_mock]",
        " | openai output prove --receipt <path>",
        " | promptfoo prove --receipt <path>",
        " | performance prove --receipt <path>",
        " | self update-goal eligibility --receipt <path>; ultragoal-validator",
        " compatibility commands remain routed through the same parser",
    )
}
