pub(crate) fn text() -> &'static str {
    concat!(
        "usage: ultragoal <command>\n",
        "Harness Ultragoal CLI\n",
        "\n",
        "Routine validation:\n",
        "  ultragoal loop run --tier hot --cache-mode verified-local --jobs auto\n",
        "    Default source-local repair loop. Computes current state, runs the\n",
        "    affected verified incremental graph, reports timing/cache/worker state,\n",
        "    and preserves a source-local claim ceiling.\n",
        "  ultragoal current-state --json\n",
        "    Bounded typed read model for current digest, stale evidence, first\n",
        "    blocker, observability control-board status, and next narrow repair.\n",
        "  ultragoal routine check [--target-repo <path>] [--receipt <path>]\n",
        "    Ordinary source-local operator path. Supports routine_usability only;\n",
        "    unsupported claims include readiness, release, final_packet, registry,\n",
        "    reviewer exposure, install/cache parity, completion, and update_goal.\n",
        "\n",
        "First plugin-activated repo path:\n",
        "  ultragoal fit-repo prove --receipt-dir validation_artifacts/harness\n",
        "    Mints fit-repo, product-fitness, and product-journey receipts for a\n",
        "    plugin-activated repository without implying readiness or release.\n",
        "\n",
        "Target repo path:\n",
        "  ultragoal target-repo audit --surface-root <repo> --receipt <path>\n",
        "    Proves target-repo capability for the named repo surface only.\n",
        "\n",
        "Source-local proof paths:\n",
        "  ultragoal source audit --receipt <path> [--red-report <path>]\n",
        "    [--mode hot|focused|standard|strict|strict_fixtures|strict_coverage|strict_final]\n",
        "    [--jobs N]\n",
        "  ultragoal red fixture report [--report <path>]\n",
        "  ultragoal schema validation [--schema <id> --file <path>] [--jobs N]\n",
        "  ultragoal line-caps check --strict [--jobs N]\n",
        "  ultragoal namespace check --strict [--jobs N]\n",
        "  ultragoal mandatory-law validation [--law <id>] [--jobs N]\n",
        "  ultragoal source-obligations check --strict [--obligation <id>] [--jobs N]\n",
        "  ultragoal foundational-trace check --strict [--obligation <id>] [--jobs N]\n",
        "  ultragoal package digest\n",
        "  ultragoal package-digest\n",
        "  ultragoal coverage prove --receipt <path> [--jobs N] [--validate-existing]\n",
        "  ultragoal performance prove --receipt <path>\n",
        "  ultragoal rust <toolchain verify|fast|standard|release|clean-proof|watch|\n",
        "    memory prove|dependency audit|coverage prove --exact|workspace topology check> --receipt <path>\n",
        "\n",
        "Package, packet, and live-surface boundaries:\n",
        "  ultragoal install audit --receipt <path> [--installed-root <path>]\n",
        "  ultragoal cache audit --receipt <path> [--cache-root <path>]\n",
        "  ultragoal review-target build --receipt <path>\n",
        "  ultragoal archive build --zip <path> --receipt <path>\n",
        "  ultragoal review-round verify --receipt <path> --validator-receipt <path>\n",
        "    --review-target-receipt <path> --archive-receipt <path>\n",
        "  ultragoal final-packet prove --receipt <path>\n",
        "  ultragoal self update-goal eligibility --receipt <path>\n",
        "\n",
        "Specialized proof surfaces:\n",
        "  ultragoal product prove-cohesion\n",
        "  ultragoal product prove-fitness --receipt-dir <dir>\n",
        "  ultragoal product prove-journey [--receipt-dir <dir>]\n",
        "  ultragoal standards-gardener rebind --receipt <path>\n",
        "  ultragoal session-log hardening rebind --receipt <path>\n",
        "  ultragoal transaction finalize --receipt <path>\n",
        "  ultragoal gc <plan|dry-run|apply|verify> --receipt <path>\n",
        "  ultragoal halo capability prove --receipt <path>\n",
        "  ultragoal improvement-loop prove --receipt <path>\n",
        "  ultragoal observe <stack|logs|metrics|traces|snapshot|prove|explain-*> ...\n",
        "  ultragoal observe command-roundtrip --command <id>\n",
        "  ultragoal observe command-roundtrip --family <family>\n",
        "  ultragoal openai config prove --receipt <path>\n",
        "  ultragoal openai call prove --receipt <path> [--mode no_network|offline_fixture|local_mock]\n",
        "  ultragoal openai output prove --receipt <path>\n",
        "  ultragoal promptfoo prove --receipt <path>\n",
        "\n",
        "scripts/check is a narrow helper unless it delegates to routine check; its\n",
        "pass cannot satisfy routine_usability, product_readiness, readiness, release,\n",
        "final_packet, registry/reviewer exposure, completion, or update_goal claims.\n",
        "ultragoal-validator compatibility commands remain routed through this parser.",
    )
}
