pub fn text_ok(text: &str) -> bool {
    let meaningful = meaningful_toml_lines(&text).join("\n");
    autogenerated_comment_ok(text)
        && header_ok(&meaningful)
        && action_count(&meaningful) >= 3
        && setup_script_ok(&meaningful)
        && cleanup_script_ok(&meaningful)
        && fast_check_action_ok(&meaningful)
        && !meaningful.contains("command =")
        && !meaningful.contains("else true")
}

fn meaningful_toml_lines(text: &str) -> Vec<&str> {
    text.lines()
        .map(str::trim)
        .filter(|line| !line.is_empty() && !line.starts_with('#'))
        .collect()
}

fn action_count(text: &str) -> usize {
    text.lines().filter(|line| *line == "[[actions]]").count()
}

fn autogenerated_comment_ok(text: &str) -> bool {
    text.lines()
        .next()
        .is_some_and(|line| line == "# THIS IS AUTOGENERATED. DO NOT EDIT MANUALLY")
}

fn header_ok(text: &str) -> bool {
    text.lines().any(|line| line == "version = 1")
        && text.lines().any(|line| line.starts_with("name = \""))
}

fn setup_script_ok(text: &str) -> bool {
    let Some(section) = section_after(text, "[setup]") else {
        return false;
    };
    section.contains("script")
        && section.contains("${CODEX_WORKTREE_PATH:-$PWD}")
        && section.contains("$HOME/.codex/bin/codex-worktree-env")
}

fn cleanup_script_ok(text: &str) -> bool {
    let Some(section) = section_after(text, "[cleanup]") else {
        return false;
    };
    section.contains("script")
        && section.contains("${CODEX_WORKTREE_PATH:-$PWD}")
        && section.contains("cleanup_receipt=")
        && section.contains("find .codex-worktree -type f | sort")
        && !section.contains("find .codex-worktree -maxdepth")
        && section.contains("rm -rf .codex-worktree")
}

fn fast_check_action_ok(text: &str) -> bool {
    action_sections(text).into_iter().any(|section| {
        section.contains("name = \"Fast Check\"")
            && section.contains("script")
            && section.contains(".codex-worktree/env.sh")
            && section.contains("scripts/check is required for Fast Check")
            && section.contains("exit 2")
    })
}

fn section_after<'a>(text: &'a str, header: &str) -> Option<&'a str> {
    let start = text.find(header)?;
    let after = &text[start + header.len()..];
    let end = after
        .lines()
        .scan(0usize, |offset, line| {
            let current = *offset;
            *offset += line.len() + 1;
            Some((current, line))
        })
        .find(|(_, line)| line.starts_with('['))
        .map(|(offset, _)| offset)
        .unwrap_or(after.len());
    Some(&after[..end])
}

fn action_sections(text: &str) -> Vec<&str> {
    text.match_indices("[[actions]]")
        .map(|(start, _)| {
            let after = &text[start..];
            let end = after
                .find("\n[[actions]]")
                .filter(|offset| *offset > 0)
                .unwrap_or(after.len());
            &after[..end]
        })
        .collect()
}
