#!/usr/bin/env bash
set -euo pipefail

worktree="${CODEX_WORKTREE_PATH:-$PWD}"
cd "$worktree"
root="$(pwd -P)"

state_root="$root/.codex-worktree"
scratch="$state_root/scratch"
state="$state_root/state"
home="$state_root/home"
tmp="$state_root/tmp"
cargo_target="$state_root/cargo-target"
cargo_cov_target="$state_root/cargo-llvm-cov-target"

mkdir -p "$scratch" "$state" "$home" "$tmp" "$cargo_target" "$cargo_cov_target"

if command -v shasum >/dev/null 2>&1; then
  hash="$(printf '%s' "$root" | shasum -a 256 | awk '{print $1}')"
elif command -v sha256sum >/dev/null 2>&1; then
  hash="$(printf '%s' "$root" | sha256sum | awk '{print $1}')"
else
  hash="$(printf '%s' "$root" | cksum | awk '{print $1}')"
fi

worktree_id="${hash:0:16}"
port_hex="${hash:0:4}"
port=$((20000 + (16#$port_hex % 20000)))
env_file="$state_root/env.sh"

cat > "$env_file" <<EOF
# Generated by .codex/setup-worktree-env.sh. Do not edit.
export CODEX_WORKTREE_ROOT="$root"
export CODEX_WORKTREE_ID="$worktree_id"
export CODEX_WORKTREE_SCRATCH="$scratch"
export CODEX_WORKTREE_STATE="$state"
export CODEX_WORKTREE_HOME="$home"
export CODEX_WORKTREE_TMP="$tmp"
export CODEX_WORKTREE_PORT="$port"
export TMPDIR="$tmp"
export TMP="$tmp"
export TEMP="$tmp"
export HOST="127.0.0.1"
export CARGO_TARGET_DIR="$cargo_target"
export CARGO_LLVM_COV_TARGET_DIR="$cargo_cov_target"
EOF

if [ -f "$root/plugin-manifest-draft.json" ] && [ -f "$root/validator/Cargo.toml" ]; then
  cat >> "$env_file" <<EOF
export HARNESS_ULTRAGOAL_PLUGIN_REPO="1"
export HARNESS_ULTRAGOAL_VALIDATOR_MANIFEST="$root/plugin-manifest-draft.json"
export HARNESS_ULTRAGOAL_VALIDATOR_RECEIPT="$root/validation_artifacts/ultragoal-audit/validator-receipt.json"
EOF
fi

chmod 600 "$env_file"
printf 'Codex worktree env ready: %s\n' "$env_file"
