use std::collections::BTreeMap;

pub fn base() -> BTreeMap<String, &'static str> {
    [
        ("plugin-manifest-draft.json", "plugin-manifest.schema.json"),
        ("docs/source-cards.json", "source-cards.schema.json"),
        (
            "docs/plugin-scout-receipt.json",
            "plugin-scout-receipt.schema.json",
        ),
        (
            "templates/agent-standards/enforcement.json",
            "agent-standards-enforcement.schema.json",
        ),
        (
            "examples/generated/READY_FOR_MERGE.example.json",
            "ready-for-merge.schema.json",
        ),
        (
            "fixtures/valid/minimal-goal-run.json",
            "fixture-bundle.schema.json",
        ),
        (
            "templates/PRODUCT_COHESION_RECEIPT.json",
            "product-cohesion-receipt.schema.json",
        ),
        (
            "templates/PRODUCT_FITNESS_RECEIPT.json",
            "product-fitness-receipt.schema.json",
        ),
        (
            "validation_artifacts/harness/product-fitness-receipt.json",
            "product-fitness-receipt.schema.json",
        ),
        (
            "validation_artifacts/harness/session-log-hardening-receipt.json",
            "session-log-hardening-receipt.schema.json",
        ),
        (
            "templates/.harness/coverage-manifest.json",
            "coverage-manifest.schema.json",
        ),
        (
            "docs/law-family-aliases.json",
            "law-family-aliases.schema.json",
        ),
        (
            "docs/namespace-class-registry.json",
            "namespace-class-registry.schema.json",
        ),
        (
            "docs/openai-key-policy.json",
            "openai-key-policy.schema.json",
        ),
        (
            "docs/openai-provider-policy.json",
            "openai-provider-policy.schema.json",
        ),
        (
            "validation_artifacts/openai/config-receipt.json",
            "openai-config-receipt.schema.json",
        ),
        (
            "validation_artifacts/openai/call-receipt.json",
            "openai-call-receipt.schema.json",
        ),
        (
            "validation_artifacts/openai/model-output-authority.json",
            "openai-model-output-authority.schema.json",
        ),
        (
            "validation_artifacts/promptfoo/adapter-receipt.json",
            "promptfoo-adapter-receipt.schema.json",
        ),
        (
            "validation_artifacts/halo/capability-receipt.json",
            "halo-capability-receipt.schema.json",
        ),
        (
            "docs/improvement-loop-registry.json",
            "improvement-loop-registry.schema.json",
        ),
        (
            "validation_artifacts/improvement-loop/loop-closure-receipt.json",
            "improvement-loop-receipt.schema.json",
        ),
        (
            "fixtures/namespace/valid/namespace-class-registry-valid.json",
            "namespace-class-registry.schema.json",
        ),
        (
            "fixtures/law-surfaces/valid/runtime-tool-identity-receipt.json",
            "runtime-tool-identity-receipt.schema.json",
        ),
        (
            "fixtures/law-surfaces/valid/product-live-surface-receipt.json",
            "product-live-surface-receipt.schema.json",
        ),
        (
            "fixtures/law-surfaces/valid/transcript-quality-receipt.json",
            "transcript-quality-receipt.schema.json",
        ),
        (
            "fixtures/law-surfaces/valid/clean-checkout-command-discovery-receipt.json",
            "clean-checkout-command-discovery-receipt.schema.json",
        ),
        (
            "fixtures/law-surfaces/valid/restartable-execplan-receipt.json",
            "restartable-execplan-receipt.schema.json",
        ),
        (
            "fixtures/law-surfaces/valid/memory-context-boundary-receipt.json",
            "memory-context-boundary-receipt.schema.json",
        ),
        (
            "docs/mandatory-law-surfaces.json",
            "mandatory-law-surfaces.schema.json",
        ),
        (
            "docs/research-source-cards.json",
            "research-source-cards.schema.json",
        ),
        (
            "docs/research-source-registry.json",
            "research-source-registry.schema.json",
        ),
        (
            "docs/research-article-to-law-trace.json",
            "research-article-to-law-trace.schema.json",
        ),
        (
            "docs/plugin-cohesion-manifest.json",
            "plugin-cohesion-manifest.schema.json",
        ),
        (
            "validation_artifacts/harness/fit-repo-receipt.json",
            "fit-repo-receipt.schema.json",
        ),
        (
            "validation_artifacts/harness/plugin-product-journey-receipt.json",
            "plugin-product-journey-receipt.schema.json",
        ),
        (
            "validation_artifacts/cli/update-goal-eligibility.json",
            "cli-control-plane-receipt.schema.json",
        ),
        (
            "validation_artifacts/cli/self-law-receipt.json",
            "cli-control-plane-receipt.schema.json",
        ),
        (
            "validation_artifacts/cli/performance-receipt.json",
            "cli-performance-receipt.schema.json",
        ),
        (
            "validation_artifacts/rust/toolchain-receipt.json",
            "rust-devx-receipt.schema.json",
        ),
        (
            "validation_artifacts/rust/standard-receipt.json",
            "rust-devx-receipt.schema.json",
        ),
        (
            "validation_artifacts/rust/clean-proof-receipt.json",
            "rust-devx-receipt.schema.json",
        ),
        (
            "validation_artifacts/rust/memory-receipt.json",
            "rust-devx-receipt.schema.json",
        ),
        (
            "validation_artifacts/rust/dependency-receipt.json",
            "rust-devx-receipt.schema.json",
        ),
        (
            "validation_artifacts/gc/verify-receipt.json",
            "workspace-gc-receipt.schema.json",
        ),
        (
            "templates/validation_artifacts/harness/fit-repo-receipt.json",
            "fit-repo-receipt.schema.json",
        ),
        (
            "templates/RED_FIXTURES.json",
            "red-fixtures-catalog.schema.json",
        ),
    ]
    .into_iter()
    .map(|(path, schema)| (path.to_string(), schema))
    .collect()
}
