use crate::target_fixtures::spec::model::{TargetSpec, invalid};

pub fn push(out: &mut Vec<TargetSpec>) {
    push_required_stack(out);
    push_query_policy(out);
    push_malformed_ledgers(out);
}

fn push_required_stack(out: &mut Vec<TargetSpec>) {
    out.extend([
        invalid(
            "target-missing-observability-receipt.json",
            "fixtures/target-repo/red/missing-observability",
            "init",
            true,
            false,
            "observability-stack",
            "blocked",
        ),
        invalid(
            "target-partial-observability-receipt.json",
            "fixtures/target-repo/red/partial-observability",
            "init",
            true,
            false,
            "observability-stack",
            "blocked",
        ),
        invalid(
            "target-incomplete-observability-receipt.json",
            "fixtures/target-repo/red/incomplete-observability",
            "init",
            true,
            false,
            "observability-stack",
            "blocked",
        ),
        invalid(
            "target-invented-observability-artifact-receipt.json",
            "fixtures/target-repo/red/invented-observability-artifact",
            "init",
            true,
            false,
            "observability-stack",
            "blocked",
        ),
    ]);
}

fn push_query_policy(out: &mut Vec<TargetSpec>) {
    out.extend([
        invalid(
            "target-observability-ledger-without-query-receipt.json",
            "fixtures/target-repo/red/observability-ledger-without-query",
            "init",
            true,
            false,
            "observability-stack",
            "blocked",
        ),
        invalid(
            "target-observability-query-timeout-receipt.json",
            "fixtures/target-repo/red/observability-query-timeout",
            "init",
            true,
            false,
            "observability-stack",
            "blocked",
        ),
        invalid(
            "target-observability-query-output-too-large-receipt.json",
            "fixtures/target-repo/red/observability-query-output-too-large",
            "init",
            true,
            false,
            "observability-stack",
            "blocked",
        ),
        invalid(
            "target-observability-query-side-effect-receipt.json",
            "fixtures/target-repo/red/observability-query-side-effect",
            "init",
            true,
            false,
            "observability-stack",
            "blocked",
        ),
        invalid(
            "target-observability-shell-wrapper-receipt.json",
            "fixtures/target-repo/red/observability-shell-wrapper",
            "init",
            true,
            false,
            "observability-stack",
            "blocked",
        ),
    ]);
}

fn push_malformed_ledgers(out: &mut Vec<TargetSpec>) {
    out.extend([
        invalid(
            "target-malformed-observability-row-receipt.json",
            "fixtures/target-repo/red/malformed-observability-row",
            "init",
            true,
            false,
            "observability-stack",
            "blocked",
        ),
        invalid(
            "target-malformed-observability-json-receipt.json",
            "fixtures/target-repo/red/malformed-observability-json",
            "init",
            true,
            false,
            "observability-stack",
            "blocked",
        ),
    ]);
}
