use crate::target_fixtures::spec::model::{TargetSpec, invalid};

pub fn push(out: &mut Vec<TargetSpec>) {
    push_receipt_content(out);
    push_review_artifact_paths(out);
    push_malformed_and_primary_user(out);
}

fn push_receipt_content(out: &mut Vec<TargetSpec>) {
    push_receipt_presence(out);
    push_review_content(out);
}

fn push_receipt_presence(out: &mut Vec<TargetSpec>) {
    out.extend([
        invalid(
            "target-missing-product-cohesion-receipt.json",
            "fixtures/target-repo/red/missing-product-cohesion",
            "init",
            false,
            true,
            "product-cohesion",
            "blocked",
        ),
        invalid(
            "target-partial-product-cohesion-receipt.json",
            "fixtures/target-repo/red/partial-product-cohesion",
            "init",
            false,
            true,
            "product-cohesion",
            "blocked",
        ),
        invalid(
            "target-mismatched-product-cohesion-receipt.json",
            "fixtures/target-repo/red/mismatched-product-cohesion",
            "init",
            false,
            true,
            "product-cohesion",
            "blocked",
        ),
    ]);
}

fn push_review_content(out: &mut Vec<TargetSpec>) {
    out.extend([
        invalid(
            "target-exception-product-cohesion-receipt.json",
            "fixtures/target-repo/red/exception-product-cohesion",
            "init",
            false,
            true,
            "product-cohesion",
            "blocked",
        ),
        invalid(
            "target-empty-reviewers-product-cohesion-receipt.json",
            "fixtures/target-repo/red/empty-reviewers-product-cohesion",
            "init",
            false,
            true,
            "product-cohesion",
            "blocked",
        ),
        invalid(
            "target-self-review-product-cohesion-receipt.json",
            "fixtures/target-repo/red/self-review-product-cohesion",
            "init",
            false,
            true,
            "product-cohesion",
            "blocked",
        ),
        invalid(
            "target-reviewer-authority-content-mismatch-receipt.json",
            "fixtures/target-repo/red/reviewer-authority-content-mismatch",
            "init",
            false,
            true,
            "product-cohesion",
            "blocked",
        ),
        invalid(
            "target-product-reviewer-authority-alias-receipt.json",
            "fixtures/target-repo/red/product-reviewer-authority-alias",
            "init",
            false,
            true,
            "product-cohesion",
            "blocked",
        ),
    ]);
}

fn push_review_artifact_paths(out: &mut Vec<TargetSpec>) {
    out.extend([
        invalid(
            "target-product-review-evidence-absolute-path-receipt.json",
            "fixtures/target-repo/red/product-review-evidence-absolute-path",
            "init",
            false,
            true,
            "product-cohesion",
            "blocked",
        ),
        invalid(
            "target-product-review-evidence-parent-path-receipt.json",
            "fixtures/target-repo/red/product-review-evidence-parent-path",
            "init",
            false,
            true,
            "product-cohesion",
            "blocked",
        ),
        invalid(
            "target-product-review-evidence-symlink-path-receipt.json",
            "fixtures/target-repo/red/product-review-evidence-symlink-path",
            "init",
            false,
            true,
            "product-cohesion",
            "blocked",
        ),
        invalid(
            "target-product-review-evidence-special-path-receipt.json",
            "fixtures/target-repo/red/product-review-evidence-special-path",
            "init",
            false,
            true,
            "product-cohesion",
            "blocked",
        ),
    ]);
}

fn push_malformed_and_primary_user(out: &mut Vec<TargetSpec>) {
    out.extend([
        invalid(
            "target-malformed-product-cohesion-json-receipt.json",
            "fixtures/target-repo/red/malformed-product-cohesion-json",
            "init",
            false,
            true,
            "product-cohesion",
            "blocked",
        ),
        invalid(
            "target-missing-primary-user-product-cohesion-receipt.json",
            "fixtures/target-repo/red/missing-primary-user-product-cohesion",
            "init",
            false,
            true,
            "product-cohesion",
            "blocked",
        ),
    ]);
}
