use serde_json::json;
use std::collections::BTreeMap;

fn write_text(path: &std::path::Path, text: &str) {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).expect("parent");
    }
    std::fs::write(path, text).expect("write text");
}

fn write_json(path: &std::path::Path, value: &serde_json::Value) {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).expect("parent");
    }
    std::fs::write(path, serde_json::to_vec(value).expect("json")).expect("write json");
}

#[test]
fn filesystem_inventory_and_target_edges() {
    let root = crate::self_tests::boundaries::support::temp_root("filesystem_inventory-filesystem");
    std::fs::create_dir_all(root.join("dir")).expect("dir");
    {
        let _guard = crate::red::filesystem::fixtures::materialize(
            &root,
            &json!({"filesystem_fixtures":[{"kind":"file","path":"dir/current.txt","contents":"current"}]}),
        )
        .expect("file fixture");
        assert_eq!(
            std::fs::read_to_string(root.join("dir/current.txt")).expect("fixture text"),
            "current"
        );
    }
    assert!(!root.join("dir/current.txt").exists());

    let inventory_root =
        crate::self_tests::boundaries::support::temp_root("filesystem_inventory-inventory");
    write_text(&inventory_root.join("keep.txt"), "keep");
    write_text(&inventory_root.join("__pycache__/stale.pyc"), "bytecode");
    write_text(&inventory_root.join("target.txt"), "target");
    std::fs::create_dir_all(inventory_root.join("links")).expect("links");
    #[cfg(unix)]
    std::os::unix::fs::symlink("../target.txt", inventory_root.join("links/hidden.txt"))
        .expect("symlink");
    let manifest = json!({"resources":["keep.txt","keep.txt","missing.txt","../bad"]});
    let failures =
        crate::package::inventory::closure::inventory_closure_failures(&inventory_root, &manifest);
    assert!(failures.iter().any(|item| item.contains("invalid=")));
    assert!(
        failures
            .iter()
            .any(|item| item.contains("generated bytecode"))
    );
    assert!(failures.iter().any(|item| item.contains("missing=")));
    assert!(failures.iter().any(|item| item.contains("duplicates=")));
    #[cfg(unix)]
    assert!(failures.iter().any(|item| item.contains("symlinks=")));
    assert!(
        crate::package::inventory::closure::final_bytecode_failures(&inventory_root)
            .iter()
            .any(|item| item.contains("__pycache__"))
    );

    let target =
        crate::self_tests::boundaries::support::temp_root("filesystem_inventory-target-fixture");
    write_text(&target.join("target.txt"), "target");
    write_json(
        &target.join("validation_artifacts/product-cohesion/symlink-fixture.json"),
        &json!({
            "schema": "harness-ultragoal.target-fixture-symlink.v1",
            "link_path": "auto/created/link.txt",
            "target_path": "../../target.txt"
        }),
    );
    let fixture = crate::target_fixtures::materialize_symlink_fixture(&target)
        .expect("fixture materialized")
        .expect("fixture present");
    assert!(fixture.link.is_symlink());
    fixture.cleanup().expect("cleanup");

    let _ = std::fs::remove_dir_all(root);
    let _ = std::fs::remove_dir_all(inventory_root);
    let _ = std::fs::remove_dir_all(target);
}

#[test]
fn artifact_audit_and_receipt_edges() {
    let root = crate::self_tests::boundaries::support::temp_root("filesystem_inventory-audit");
    std::fs::create_dir_all(root.join("artifacts")).expect("artifacts");
    write_text(&root.join("artifacts/proof.json"), "{\"ok\":true}");
    write_text(&root.join("artifacts/not-json.json"), "not-json");
    write_text(&root.join("__pycache__/stale.pyc"), "bytecode");
    let digest = crate::digest::file(&root.join("artifacts/proof.json")).expect("digest");
    let bad_json_digest =
        crate::digest::file(&root.join("artifacts/not-json.json")).expect("bad digest");
    let proof = json!({"path":"artifacts/proof.json","digest":digest});
    assert!(crate::target_repo::artifact_refs::read_artifact_json(&root, &proof, "proof").is_ok());
    let malformed = json!({"path":"artifacts/not-json.json","digest":bad_json_digest});
    assert!(
        crate::target_repo::artifact_refs::read_artifact_json(&root, &malformed, "proof")
            .expect_err("malformed artifact")
            .contains("json malformed")
    );
    for item in [
        json!({"path":"","digest":crate::digest::ZERO}),
        json!({"path":"artifacts/fixture-proof.json","digest":proof["digest"]}),
        json!({"path":"../escape.json","digest":proof["digest"]}),
        json!({"path":"artifacts/proof.json","digest":crate::self_tests::boundaries::support::sha('e')}),
    ] {
        assert!(
            crate::target_repo::artifact_refs::artifact_ref_error(&root, &item, "proof").is_some()
        );
    }

    let cli_failures = crate::audit::cli::control_plane::authority::package_failures(&root);
    assert!(
        cli_failures
            .iter()
            .any(|item| item.contains("cli_control_plane_missing_artifact"))
    );
    assert!(cli_failures.iter().any(|item| item.contains(
        "cli_control_plane_package_inventory_missing:validator/src/cli/control/plane/mod.rs"
    )));
    assert!(
        cli_failures
            .iter()
            .any(|item| item.contains("cli_control_plane_schema_catalog"))
    );
    assert!(
        cli_failures
            .iter()
            .any(|item| item.contains("cli_control_plane_missing_standards_row"))
    );
    assert!(
        cli_failures
            .iter()
            .any(|item| item.contains("cli_control_plane_missing_source_obligation"))
    );
    assert!(
        cli_failures
            .iter()
            .any(|item| item.contains("cli_control_plane_missing_foundational_trace"))
    );
    assert!(
        cli_failures
            .iter()
            .any(|item| item.contains("cli_control_plane_missing_valid_fixture"))
    );
    assert!(
        cli_failures
            .iter()
            .any(|item| item.contains("cli_control_plane_missing_red_fixture"))
    );

    write_json(
        &root.join("plugin-manifest-draft.json"),
        &json!({"resources":[]}),
    );
    let perf_failures = crate::audit::cli::performance::package_failures(&root);
    assert!(
        perf_failures
            .iter()
            .any(|item| item.contains("cli_performance_missing_red_fixture"))
    );
    assert!(
        perf_failures
            .iter()
            .any(|item| item.contains("cli_performance_missing_fail_closed_receipt"))
    );

    let mut failures = BTreeMap::new();
    crate::audit::package::checks::final_hygiene_check(&root, &mut failures);
    assert!(!failures.is_empty());

    assert!(crate::audit::validate_target_receipt(&json!({"status":"pass"})).is_err());
    assert_eq!(
        crate::audit::receipt::root_identity(std::path::Path::new("/tmp/example")),
        format!(
            "package-root:{}",
            crate::digest::bytes("/tmp/example".as_bytes())
        )
    );

    let store = crate::schema_catalog::load(&crate::self_tests::boundaries::support::repo_root());
    let registry =
        root.join("validation_artifacts/ultragoal-audit/active-registry-exposure-current.json");
    write_json(
        &registry,
        &json!({
            "schema":"harness-ultragoal.codex-registry-exposure.v1",
            "captured_at":"2026-06-24T00:00:00Z",
            "source":"wrong",
            "agent_types":[
                {
                    "agent_type":"harness_contract_claim_falsifier",
                    "persona":"wrong",
                    "custom_agent_path":"wrong.toml",
                    "disk_cache_synced":false,
                    "global_toml_present":false,
                    "exposed":false
                }
            ]
        }),
    );
    let self_law = crate::audit::plugin::laws::package_failures(&root, &store);
    let registry_value = crate::json_boundary::read_json(&registry).expect("registry json");
    let strict_registry =
        crate::audit::plugin::registry::value_failures(&root, &store, &registry_value);
    assert!(
        strict_registry
            .iter()
            .any(|item| item.contains("plugin_self_law_registry_agent_mismatch"))
    );
    assert!(
        strict_registry
            .iter()
            .any(|item| item.contains("plugin_self_law_registry_agent_not_current"))
    );
    assert!(
        self_law
            .iter()
            .any(|item| item.contains("plugin_self_law_registry_guard_wrong_source"))
    );
    assert!(
        self_law
            .iter()
            .any(|item| item.contains("plugin_self_law_registry_guard_failure_reason_missing"))
    );

    let _ = std::fs::remove_dir_all(root);
}
