#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum LegacyCommand {
    Archive,
    Audit,
    Control,
    Coverage,
    CurrentState,
    FinalPacket,
    FixtureSchedule,
    FoundationalTrace,
    Garbage,
    Halo,
    Help,
    ImpactedRustTests,
    ImprovementLoop,
    LineCaps,
    LiveLoop,
    MandatoryLawValidation,
    Namespace,
    Observe,
    OpenAi,
    PackageDigest,
    Performance,
    Product,
    Promptfoo,
    RedReport,
    ReviewRound,
    ReviewTarget,
    Routine,
    Rust,
    SchemaValidation,
    SemanticReceipts,
    Session,
    SourceObligations,
    Standards,
    TransactionalFinalization,
    TypedBoundaries,
}

impl LegacyCommand {
    pub const fn stable_name(self) -> &'static str {
        match self {
            Self::Archive => "Archive",
            Self::Audit => "Audit",
            Self::Control => "Control",
            Self::Coverage => "Coverage",
            Self::CurrentState => "CurrentState",
            Self::FinalPacket => "FinalPacket",
            Self::FixtureSchedule => "FixtureSchedule",
            Self::FoundationalTrace => "FoundationalTrace",
            Self::Garbage => "Garbage",
            Self::Halo => "Halo",
            Self::Help => "Help",
            Self::ImpactedRustTests => "ImpactedRustTests",
            Self::ImprovementLoop => "ImprovementLoop",
            Self::LineCaps => "LineCaps",
            Self::LiveLoop => "LiveLoop",
            Self::MandatoryLawValidation => "MandatoryLawValidation",
            Self::Namespace => "Namespace",
            Self::Observe => "Observe",
            Self::OpenAi => "OpenAi",
            Self::PackageDigest => "PackageDigest",
            Self::Performance => "Performance",
            Self::Product => "Product",
            Self::Promptfoo => "Promptfoo",
            Self::RedReport => "RedReport",
            Self::ReviewRound => "ReviewRound",
            Self::ReviewTarget => "ReviewTarget",
            Self::Routine => "Routine",
            Self::Rust => "Rust",
            Self::SchemaValidation => "SchemaValidation",
            Self::SemanticReceipts => "SemanticReceipts",
            Self::Session => "Session",
            Self::SourceObligations => "SourceObligations",
            Self::Standards => "Standards",
            Self::TransactionalFinalization => "TransactionalFinalization",
            Self::TypedBoundaries => "TypedBoundaries",
        }
    }

    pub const fn canonical_target(self) -> &'static str {
        match self {
            Self::Archive => "package/migrate",
            Self::Audit => "inspect/prove",
            Self::Control => "inspect/next",
            Self::Coverage => "check",
            Self::CurrentState => "inspect",
            Self::FinalPacket => "prove/package",
            Self::FixtureSchedule => "check/eval/prove",
            Self::FoundationalTrace => "inspect/prove",
            Self::Garbage => "migrate",
            Self::Halo => "prove or retire after semantic inventory",
            Self::Help => "typed parser help; zero-write",
            Self::ImpactedRustTests => "check",
            Self::ImprovementLoop => "eval",
            Self::LineCaps => "check",
            Self::LiveLoop => "goal-run plus check/diagnose",
            Self::MandatoryLawValidation => "prove",
            Self::Namespace => "inspect/migrate",
            Self::Observe => "observe/diagnose",
            Self::OpenAi => "eval/observe adapter",
            Self::PackageDigest => "package/inspect",
            Self::Performance => "check/eval",
            Self::Product => "inspect/prove",
            Self::Promptfoo => "eval adapter",
            Self::RedReport => "diagnose/prove",
            Self::ReviewRound => "prove",
            Self::ReviewTarget => "inspect",
            Self::Routine | Self::Rust | Self::SchemaValidation => "check",
            Self::SemanticReceipts => "inspect projection; receipt authority retired",
            Self::Session => "inspect/observe",
            Self::SourceObligations => "inspect/prove",
            Self::Standards => "inspect/eval/migrate",
            Self::TransactionalFinalization => "prove; finalizer authority retired",
            Self::TypedBoundaries => "check/prove",
        }
    }
}
