use super::{SourceRoot, lines};

const AGGREGATE: &str = "migration/generated-surface-authority.json";
const SHARD: &str = "migration/generated-surface-authority/fixture.json";
const OUTPUT: &str = "templates/AGENTS.md";
const SOURCE: &str = "AGENTS.md";

#[test]
fn exact_generator_source_and_command_proof_is_required() {
    let root = SourceRoot::new("generated");
    let source = lines(251);
    let output = format!(
        "<!-- @generated by scripts/project-agent-standards; source: {SOURCE}; do not edit -->\n\n{source}"
    );
    root.write(SOURCE, &source);
    root.write(OUTPUT, &output);
    let aggregate_base = read(&root, AGGREGATE);
    let shard_base = read(&root, SHARD);
    let digest = crate::digest::bytes(output.as_bytes()).replace("sha256:", "");
    let row = format!(
        "{{\n      \"disposition\": \"source_projection\",\n      \"output\": \"{OUTPUT}\",\n      \"generator\": \"scripts/project-agent-standards\",\n      \"canonical_sources\": [\n        \"{SOURCE}\"\n      ],\n      \"regeneration_command\": \"scripts/project-agent-standards write\",\n      \"output_sha256\": \"{digest}\"\n    }}"
    );
    let definition = format!(
        "{{\n      \"disposition\": \"source_projection\",\n      \"output\": \"{OUTPUT}\",\n      \"generator\": \"scripts/project-agent-standards\",\n      \"canonical_sources\": [\n        \"{SOURCE}\"\n      ],\n      \"regeneration_command\": \"scripts/project-agent-standards write\"\n    }}"
    );
    root.write(AGGREGATE, &append_surfaces(&aggregate_base, &row, 1));
    root.write(SHARD, &append_surfaces(&shard_base, &definition, 1));
    let inventory = crate::audit::source_governance::capture(root.path()).expect("registered");
    assert!(
        !crate::audit::source_governance::line_cap_failures(&inventory)
            .iter()
            .any(|failure| failure.contains(OUTPUT))
    );

    root.write(SHARD, &append_surfaces(&shard_base, &definition, 2));
    let duplicate = crate::audit::source_governance::capture(root.path()).expect_err("duplicate");
    assert!(
        duplicate
            .iter()
            .any(|failure| failure.contains("generated_authority_shard_output_duplicate")),
        "{duplicate:?}"
    );

    root.write(AGGREGATE, &aggregate_base);
    root.write(SHARD, &shard_base);
    let missing = crate::audit::source_governance::capture(root.path()).expect_err("unregistered");
    assert!(
        missing
            .iter()
            .any(|failure| failure.contains("generated_source_unregistered")),
        "{missing:?}"
    );
}

#[test]
fn missing_registry_does_not_hide_independent_generated_marker_finding() {
    let root = SourceRoot::new("generated-missing-registry");
    root.write(
        OUTPUT,
        "<!-- @generated by fixture; do not edit -->\n# Unregistered\n",
    );
    std::fs::remove_file(root.path().join(AGGREGATE)).expect("remove generated registry");
    let failures = crate::audit::source_governance::capture(root.path()).expect_err("invalid");
    assert!(
        failures
            .iter()
            .any(|failure| failure == "generated_source_registry_source_missing"),
        "{failures:?}"
    );
    assert!(
        failures
            .iter()
            .any(|failure| failure == &format!("generated_source_unregistered:{OUTPUT}")),
        "{failures:?}"
    );
}

#[test]
fn invalid_registry_does_not_hide_independent_generated_marker_finding() {
    let root = SourceRoot::new("generated-invalid-registry");
    root.write(
        OUTPUT,
        "<!-- @generated by fixture; do not edit -->\n# Unregistered\n",
    );
    root.write(AGGREGATE, "{");
    let failures = crate::audit::source_governance::capture(root.path()).expect_err("invalid");
    assert!(
        failures
            .iter()
            .any(|failure| failure.starts_with("generated_source_registry_invalid:")),
        "{failures:?}"
    );
    assert!(
        failures
            .iter()
            .any(|failure| failure == &format!("generated_source_unregistered:{OUTPUT}")),
        "{failures:?}"
    );
}

fn read(root: &SourceRoot, relative: &str) -> String {
    std::fs::read_to_string(root.path().join(relative)).expect("fixture authority")
}

fn append_surfaces(document: &str, surface: &str, copies: usize) -> String {
    let marker = "\n  ]\n}\n";
    let insertion = (0..copies)
        .map(|_| format!(",\n    {surface}"))
        .collect::<String>();
    document.replacen(marker, &format!("{insertion}{marker}"), 1)
}
