use super::*;

#[test]
fn virtual_workspace_discovers_all_package_roots_and_targets() {
    let project = Project::clean();
    project.write(
        "Cargo.toml",
        "[workspace]\nmembers=[\"crates/a\",\"crates/b\"]\nresolver=\"3\"\n",
    );
    std::fs::remove_file(project.0.join("src/lib.rs")).unwrap();
    for name in ["a", "b"] {
        project.write(
            &format!("crates/{name}/Cargo.toml"),
            &format!("[package]\nname=\"{name}\"\nversion=\"0.1.0\"\nedition=\"2024\"\n"),
        );
        project.write(
            &format!("crates/{name}/src/lib.rs"),
            "pub fn pure() -> bool { true }",
        );
    }
    project.write("Cargo.lock", "# This file is automatically @generated by Cargo.\nversion=4\n[[package]]\nname=\"a\"\nversion=\"0.1.0\"\n[[package]]\nname=\"b\"\nversion=\"0.1.0\"\n");
    let audit = project.audit();
    let entries = audit["inventory"]["entrypoints"].as_array().unwrap();
    for name in ["a", "b"] {
        assert!(
            entries.contains(&json!(format!("crates/{name}/src/lib.rs"))),
            "{audit:#}"
        );
        assert!(has(
            &audit,
            &format!("source_map_missing:crates/{name}/src/lib.rs")
        ));
    }
    assert!(!has(&audit, "cargo_metadata_missing_package:"), "{audit:#}");
}

#[test]
fn workspace_member_in_pruned_directory_cannot_disappear() {
    let project = Project::clean();
    project.write(
        "Cargo.toml",
        "[workspace]\nmembers=[\"target/member\"]\nresolver=\"3\"\n",
    );
    project.write(
        "target/member/Cargo.toml",
        "[package]\nname=\"member\"\nversion=\"0.1.0\"\nedition=\"2024\"\n",
    );
    project.write("target/member/src/lib.rs", "pub fn hidden() {}");
    project.write("Cargo.lock", "# This file is automatically @generated by Cargo.\nversion=4\n[[package]]\nname=\"member\"\nversion=\"0.1.0\"\n");
    assert!(has(
        &project.audit(),
        "cargo_package_ungoverned:target/member/Cargo.toml"
    ));
}

#[test]
fn path_dependency_outside_project_is_a_coverage_failure() {
    let project = Project::clean();
    let outside = Project::clean();
    project.write("Cargo.toml", &format!(
        "[package]\nname=\"consumer\"\nversion=\"0.1.0\"\nedition=\"2024\"\n[dependencies]\nlegibility-receiving={{path={:?}}}\n[workspace]\n",
        outside.0.to_str().unwrap()));
    let output = std::process::Command::new("cargo")
        .args(["generate-lockfile", "--offline"])
        .current_dir(&project.0)
        .output()
        .unwrap();
    assert!(output.status.success(), "{output:?}");
    assert!(
        has(&project.audit(), "cargo_package_outside_project:"),
        "{}",
        project.audit()
    );
}
