use serde_json::Value;
use std::{collections::BTreeSet, path::Path, process::Command};

#[derive(Debug)]
pub struct DirectDependency {
    pub manifest: String,
    pub crate_name: String,
    pub requirement: String,
}

#[derive(Default)]
pub struct Metadata {
    pub dependencies: Vec<DirectDependency>,
    pub entrypoints: Vec<String>,
    pub verified_locks: Vec<String>,
    pub failures: Vec<String>,
}

pub fn collect(root: &Path, inventory: &crate::inventory::Inventory) -> Metadata {
    let mut metadata = Metadata::default();
    let manifests: BTreeSet<_> = inventory
        .files
        .keys()
        .filter(|p| Path::new(p).file_name().is_some_and(|n| n == "Cargo.toml"))
        .cloned()
        .collect();
    if manifests.is_empty() {
        metadata
            .failures
            .push("rust_semantics_unavailable:no_Cargo_manifest".into());
    }
    let mut checked = BTreeSet::new();
    for manifest in &manifests {
        if checked.contains(manifest) {
            continue;
        }
        let output = Command::new("cargo")
            .args([
                "metadata",
                "--locked",
                "--offline",
                "--format-version",
                "1",
                "--manifest-path",
            ])
            .arg(root.join(manifest))
            .current_dir(root)
            .output();
        let output = match output {
            Ok(output) if output.status.success() => output,
            Ok(output) => {
                metadata.failures.push(format!(
                    "cargo_metadata_failed:{manifest}:{}:{}",
                    output.status,
                    String::from_utf8_lossy(&output.stderr)
                ));
                continue;
            }
            Err(error) => {
                metadata
                    .failures
                    .push(format!("cargo_metadata_launch:{manifest}:{error}"));
                continue;
            }
        };
        match serde_json::from_slice::<Value>(&output.stdout) {
            Ok(value) => ingest(
                root,
                manifest,
                &value,
                &manifests,
                &mut checked,
                &mut metadata,
            ),
            Err(error) => metadata
                .failures
                .push(format!("cargo_metadata_json:{manifest}:{error}")),
        }
    }
    metadata.entrypoints.sort();
    metadata.entrypoints.dedup();
    metadata.verified_locks.sort();
    metadata.verified_locks.dedup();
    metadata
}

fn relative(root: &Path, path: &str) -> Option<String> {
    let path = Path::new(path).strip_prefix(root).ok()?.to_str()?;
    crate::inventory::safe_path(path).then(|| path.into())
}

fn ingest(
    root: &Path,
    requested: &str,
    value: &Value,
    manifests: &BTreeSet<String>,
    checked: &mut BTreeSet<String>,
    metadata: &mut Metadata,
) {
    let Some(packages) = value["packages"].as_array() else {
        metadata
            .failures
            .push(format!("cargo_metadata_missing_packages:{requested}"));
        return;
    };
    let members: BTreeSet<_> = value["workspace_members"]
        .as_array()
        .into_iter()
        .flatten()
        .filter_map(Value::as_str)
        .collect();
    for package in packages {
        let path = package["manifest_path"].as_str().unwrap_or("");
        if !package["source"].is_null() {
            continue;
        }
        let Some(manifest) = relative(root, path) else {
            metadata
                .failures
                .push(format!("cargo_package_outside_project:{path}"));
            continue;
        };
        if !manifests.contains(&manifest) {
            metadata
                .failures
                .push(format!("cargo_package_ungoverned:{manifest}"));
            continue;
        }
        if checked.insert(manifest.clone()) {
            package_metadata(root, &manifest, package, metadata);
        }
    }
    for member in members {
        if !packages.iter().any(|p| p["id"].as_str() == Some(member)) {
            metadata
                .failures
                .push(format!("cargo_workspace_member_missing:{member}"));
        }
    }
    let workspace = value["workspace_root"].as_str().unwrap_or("");
    let lock = Path::new(workspace).join("Cargo.lock");
    let Some(relative) = lock.to_str().and_then(|p| relative(root, p)) else {
        metadata
            .failures
            .push(format!("cargo_workspace_outside_project:{workspace}"));
        return;
    };
    match std::fs::symlink_metadata(&lock) {
        Ok(m) if m.is_file() && !m.file_type().is_symlink() => {
            let raw = std::fs::read_to_string(&lock).unwrap_or_default();
            if raw.starts_with("# This file is automatically @generated by Cargo.") {
                metadata.verified_locks.push(relative);
            } else {
                metadata
                    .failures
                    .push(format!("generated_lock_header_invalid:{relative}"));
            }
        }
        _ => metadata
            .failures
            .push(format!("generated_lock_missing_or_linked:{relative}")),
    }
}

fn package_metadata(root: &Path, manifest: &str, package: &Value, metadata: &mut Metadata) {
    let Some(dependencies) = package["dependencies"].as_array() else {
        metadata
            .failures
            .push(format!("cargo_metadata_missing_dependencies:{manifest}"));
        return;
    };
    for dependency in dependencies {
        let name = dependency["rename"]
            .as_str()
            .or_else(|| dependency["name"].as_str());
        match (name, dependency["req"].as_str()) {
            (Some(name), Some(req)) => {
                let name = name.replace('-', "_");
                if !metadata
                    .dependencies
                    .iter()
                    .any(|d| d.manifest == manifest && d.crate_name == name && d.requirement == req)
                {
                    metadata.dependencies.push(DirectDependency {
                        manifest: manifest.into(),
                        crate_name: name,
                        requirement: req.into(),
                    });
                }
            }
            _ => metadata
                .failures
                .push(format!("cargo_metadata_dependency_shape:{manifest}")),
        }
    }
    let Some(targets) = package["targets"].as_array() else {
        metadata
            .failures
            .push(format!("cargo_metadata_missing_targets:{manifest}"));
        return;
    };
    for target in targets {
        let path = target["src_path"].as_str().unwrap_or("");
        match relative(root, path) {
            Some(path) => metadata.entrypoints.push(path),
            None => metadata
                .failures
                .push(format!("cargo_target_outside_project:{manifest}:{path}")),
        }
    }
}
