"""Deterministic agent-standards projection rendering."""

from __future__ import annotations

import csv
from dataclasses import dataclass
import io
import json
from pathlib import Path

from .contracts import (
    AuditRow,
    AuditStatus,
    EnforcementStatus,
    PolicyRow,
    audit_row,
    policy_row,
    shard_rows,
)
from repository_projection.atomic_file import ProjectionFileMode, regular_bytes


ROOT_DOCUMENTS = (
    "AGENTS.md", "AGENT_STANDARDS.md", "PLANS.md", "PRODUCT_SUCCESS_CONTRACT.md",
)
STANDARD_DOCUMENTS = (
    "README.md", "01-namespace-and-progressive-disclosure.md",
    "02-boundaries-validation-and-enforcement.md",
    "03-execplans-worktrees-and-orchestration.md",
    "04-security-reliability-and-product-cohesion.md",
    "05-review-and-completion.md", "06-standards-gardening.md",
    "07-cli-authority-and-proof-surfaces.md",
    "08-observability-and-repair-loop.md",
    "09-product-success-and-quality-in-use.md",
    "10-plugin-activation-and-distribution-surfaces.md",
    "11-research-improvement-and-quality-gates.md",
    "12-tool-risk-and-runtime-substrates.md",
)
SCRIPT_PROJECTIONS = (
    "scripts/check-agent-standards",
    "scripts/agent_standards_validation/__init__.py",
    "scripts/agent_standards_validation/command.py",
    "scripts/agent_standards_validation/contracts.py",
)
POLICY_SCHEMA = "harness-ultragoal.agent-standards-policy-shard.v1"
AUDIT_SCHEMA = "harness-ultragoal.agent-standards-audit-shard.v1"
POLICY_FIELDS = tuple(
    PolicyRow("", "", "", EnforcementStatus.BLOCKED, "", "", "", "", "", ()).fields()
)
AUDIT_FIELDS = tuple(
    AuditRow("", AuditStatus.BLOCKED, "", "", "", "").fields()
)


@dataclass(frozen=True)
class RenderedOutput:
    content: bytes
    mode: ProjectionFileMode


def regular_output(content: bytes) -> RenderedOutput:
    return RenderedOutput(content, ProjectionFileMode.REGULAR)


def load_policy_rows(directory: Path) -> list[PolicyRow]:
    rows: list[PolicyRow] = []
    for path in sorted(directory.glob("*.json")):
        rows.extend(policy_row(row, path) for row in shard_rows(regular_bytes(path), path, POLICY_SCHEMA))
    return unique_sorted_policy(rows, directory)


def load_audit_rows(directory: Path) -> list[AuditRow]:
    rows: list[AuditRow] = []
    for path in sorted(directory.glob("*.json")):
        rows.extend(audit_row(row, path) for row in shard_rows(regular_bytes(path), path, AUDIT_SCHEMA))
    identities = [row.standard_id for row in rows]
    if not identities or len(set(identities)) != len(identities):
        raise ValueError(f"missing or duplicate audit identity: {directory}")
    return sorted(rows, key=lambda row: row.standard_id)


def unique_sorted_policy(rows: list[PolicyRow], directory: Path) -> list[PolicyRow]:
    identities = [row.identity for row in rows]
    if not identities or len(set(identities)) != len(identities):
        raise ValueError(f"missing or duplicate policy identity: {directory}")
    return sorted(rows, key=lambda row: row.identity)


def json_bytes(payload: object) -> bytes:
    return (json.dumps(payload, indent=2, ensure_ascii=False) + "\n").encode()


def tsv_bytes(rows: list[dict[str, object]], fields: tuple[str, ...]) -> bytes:
    stream = io.StringIO(newline="")
    writer = csv.DictWriter(stream, fieldnames=fields, delimiter="\t", lineterminator="\n")
    writer.writeheader()
    for row in rows:
        projected = dict(row)
        refs = projected.get("required_execplan_refs")
        if isinstance(refs, list):
            projected["required_execplan_refs"] = ";".join(str(item) for item in refs)
        writer.writerow(projected)
    return stream.getvalue().encode()


def marked_projection(source: str, content: bytes) -> bytes:
    marker = f"<!-- @generated by scripts/project-agent-standards; source: {source}; do not edit -->\n\n"
    return marker.encode() + content


def expected_outputs(root: Path) -> dict[Path, RenderedOutput]:
    policy = load_policy_rows(root / "agent-standards" / "policy")
    audits = load_audit_rows(root / "agent-standards" / "audit")
    policy_maps = [row.fields() for row in policy]
    policy_json = json_bytes({"schema": "harness-ultragoal.agent-standards-enforcement.v1", "rows": policy_maps})
    policy_tsv = tsv_bytes(policy_maps, POLICY_FIELDS)
    audit_tsv = tsv_bytes([row.fields() for row in audits], AUDIT_FIELDS)
    outputs: dict[Path, RenderedOutput] = {}
    for name in ROOT_DOCUMENTS:
        outputs[root / "templates" / name] = regular_output(
            marked_projection(name, regular_bytes(root / name))
        )
    for name in STANDARD_DOCUMENTS:
        source = f"agent-standards/{name}"
        outputs[root / "templates" / source] = regular_output(
            marked_projection(source, regular_bytes(root / source))
        )
    for source in SCRIPT_PROJECTIONS:
        mode = (
            ProjectionFileMode.EXECUTABLE
            if source == "scripts/check-agent-standards"
            else ProjectionFileMode.REGULAR
        )
        outputs[root / "templates" / source] = RenderedOutput(
            regular_bytes(root / source), mode
        )
    for base in (root / "agent-standards", root / "templates" / "agent-standards"):
        outputs[base / "enforcement.json"] = regular_output(policy_json)
        outputs[base / "enforcement.tsv"] = regular_output(policy_tsv)
        outputs[base / "enforcement-audit.tsv"] = regular_output(audit_tsv)
    return outputs
