use serde_json::Value;
use std::collections::BTreeSet;
use std::path::Path;

mod package_entries;
pub use package_entries::actual_files;
use package_entries::symlink_entries;

pub fn inventory_closure_failures(root: &Path, manifest: &Value) -> Vec<String> {
    let listed = crate::package::inventory::inventory_paths(manifest);
    inventory_closure_failures_inner(root, &listed).unwrap_or_else(|failures| failures)
}

fn inventory_closure_failures_inner(
    root: &Path,
    listed: &[String],
) -> Result<Vec<String>, Vec<String>> {
    let comparable = listed
        .iter()
        .filter(|rel| !listed_local_only(rel))
        .cloned()
        .collect::<Vec<_>>();
    let actual = scan_or_fail(actual_files(root))?;
    let symlinks = scan_or_fail(symlink_entries(root))?;
    let invalid = invalid_listed_paths(root, listed);
    let valid = valid_listed_paths(root, &comparable);
    let listed_set = valid.iter().cloned().collect::<BTreeSet<_>>();
    let actual_set = actual.iter().cloned().collect::<BTreeSet<_>>();
    let bytecode = bytecode_files(&actual);
    let missing = actual_set
        .difference(&listed_set)
        .take(10)
        .cloned()
        .collect::<Vec<_>>();
    let nonexistent = nonexistent_listed_paths(root, &valid);
    let duplicates = duplicate_listed_paths(&comparable);
    let mut failures = Vec::new();
    push_inventory_failures(
        &mut failures,
        InventoryFailureParts {
            invalid: &invalid,
            bytecode: &bytecode,
            missing: &missing,
            nonexistent: &nonexistent,
            duplicates: &duplicates,
            symlinks: &symlinks,
            actual_len: actual.len(),
            listed_len: comparable.len(),
        },
    );
    Ok(failures)
}

fn listed_local_only(rel: &str) -> bool {
    rel.starts_with("validation_artifacts/")
}

fn scan_or_fail(result: Result<Vec<String>, String>) -> Result<Vec<String>, Vec<String>> {
    result.map_err(|err| vec![err])
}

fn invalid_listed_paths(root: &Path, listed: &[String]) -> Vec<String> {
    listed
        .iter()
        .filter_map(|rel| {
            crate::package::inventory::package_path_error(root, rel)
                .map(|err| format!("{rel}: {err}"))
        })
        .collect()
}

fn valid_listed_paths(root: &Path, listed: &[String]) -> Vec<String> {
    listed
        .iter()
        .filter(|rel| crate::package::inventory::package_path_error(root, rel).is_none())
        .cloned()
        .collect()
}

fn bytecode_files(actual: &[String]) -> Vec<String> {
    actual
        .iter()
        .filter(|p| p.contains("__pycache__") || p.ends_with(".pyc") || p.ends_with(".pyo"))
        .cloned()
        .collect()
}

fn nonexistent_listed_paths(root: &Path, valid: &[String]) -> Vec<String> {
    valid
        .iter()
        .filter(|rel| {
            crate::package::inventory::resolve(root, rel)
                .map(|p| !p.is_file())
                .unwrap_or(true)
        })
        .take(10)
        .cloned()
        .collect()
}

fn duplicate_listed_paths(listed: &[String]) -> BTreeSet<String> {
    listed
        .iter()
        .filter(|rel| listed.iter().filter(|other| *other == *rel).count() > 1)
        .cloned()
        .collect()
}

struct InventoryFailureParts<'a> {
    invalid: &'a [String],
    bytecode: &'a [String],
    missing: &'a [String],
    nonexistent: &'a [String],
    duplicates: &'a BTreeSet<String>,
    symlinks: &'a [String],
    actual_len: usize,
    listed_len: usize,
}

fn push_inventory_failures(failures: &mut Vec<String>, parts: InventoryFailureParts<'_>) {
    if !parts.invalid.is_empty() {
        failures.push(format!(
            "invalid={}",
            parts.invalid[..parts.invalid.len().min(10)].join(",")
        ));
    }
    if !parts.bytecode.is_empty() {
        failures.push(format!(
            "generated bytecode not allowed: {}",
            parts.bytecode[..parts.bytecode.len().min(10)].join(",")
        ));
    }
    if !parts.symlinks.is_empty() {
        failures.push(format!(
            "symlinks={}",
            parts.symlinks[..parts.symlinks.len().min(10)].join(",")
        ));
    }
    if !parts.missing.is_empty() || !parts.nonexistent.is_empty() {
        failures.push(format!(
            "missing={:?} nonexistent={:?}",
            parts.missing, parts.nonexistent
        ));
    }
    if !parts.duplicates.is_empty() || parts.listed_len != parts.actual_len {
        failures.push(format!(
            "duplicates={:?} actual={} listed={}",
            parts.duplicates, parts.actual_len, parts.listed_len
        ));
    }
}

#[cfg(test)]
mod scan_tests {
    #[test]
    fn scan_or_fail_converts_scan_error_to_failures() {
        assert_eq!(
            super::scan_or_fail(Err("walk failed: denied".to_string())).expect_err("scan error"),
            vec!["walk failed: denied".to_string()]
        );
    }
}

#[cfg(test)]
mod tests {
    use super::inventory_closure_failures;
    use serde_json::json;

    #[cfg(unix)]
    #[test]
    fn unlisted_symlink_is_inventory_failure() {
        let root =
            std::env::temp_dir().join(format!("ultragoal-symlink-test-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&root);
        std::fs::create_dir_all(root.join("fixtures")).expect("create temp fixture root");
        std::fs::write(root.join("target-file.txt"), "target").expect("write temp target");
        std::os::unix::fs::symlink("../target-file.txt", root.join("fixtures/hidden.md"))
            .expect("create temp symlink");
        let failures = inventory_closure_failures(&root, &json!({}));
        let _ = std::fs::remove_dir_all(&root);
        assert!(failures.iter().any(|failure| failure.contains("symlinks=")));
    }
}
