pub(crate) const FOUNDATIONAL_AUTHORITY_READERS: &[ReaderSpec] = &[
    reader!(
        "validator/src/agent_manifest.rs",
        "../agent_manifest.rs",
        false
    ),
    reader!("validator/src/agent_roles.rs", "../agent_roles.rs", false),
    reader!(
        "validator/src/audit/contract.rs",
        "../audit/contract.rs",
        false
    ),
    reader!(
        "validator/src/audit/coverage/scope/roots.rs",
        "../audit/coverage/scope/roots.rs",
        true
    ),
    reader!(
        "validator/src/audit/plugin/product/cohesion/manifest.rs",
        "../audit/plugin/product/cohesion/manifest.rs",
        false
    ),
    reader!(
        "validator/src/audit/plugin/product/cohesion/mod.rs",
        "../audit/plugin/product/cohesion/mod.rs",
        false
    ),
    reader!(
        "validator/src/inventory/components.rs",
        "components.rs",
        false
    ),
    reader!(
        "validator/src/inventory/registry/topology.rs",
        "registry/topology.rs",
        false
    ),
    reader!(
        "validator/src/package/inventory/mod.rs",
        "../package/inventory/mod.rs",
        false
    ),
    reader!(
        "validator/src/claim_semantics/plugin_policy/mod.rs",
        "../claim_semantics/plugin_policy/mod.rs",
        true
    ),
    reader!(
        "validator/src/claim_semantics/coverage/receipt/exclusions.rs",
        "../claim_semantics/coverage/receipt/exclusions.rs",
        true
    ),
    reader!(
        "validator/src/claim_semantics/retired_reviewer_policy.rs",
        "../claim_semantics/retired_reviewer_policy.rs",
        true
    ),
    reader!(
        "validator/src/audit/plugin/registry/mod.rs",
        "../audit/plugin/registry/mod.rs",
        false
    ),
    reader!(
        "validator/src/audit/plugin/registry/live/mod.rs",
        "../audit/plugin/registry/live/mod.rs",
        true
    ),
    reader!(
        "validator/src/audit/plugin/registry/live/raw.rs",
        "../audit/plugin/registry/live/raw.rs",
        true
    ),
    reader!(
        "validator/src/audit/plugin/registry/live/reviewers.rs",
        "../audit/plugin/registry/live/reviewers.rs",
        false
    ),
];
