pub(crate) const RUNTIME_ROUTING_READERS: &[ReaderSpec] = &[
    reader!(
        "validator/src/inventory/discovery.rs",
        "discovery.rs",
        false
    ),
    reader!(
        "validator/src/inventory/legacy/matchers.rs",
        "legacy/matchers.rs",
        true
    ),
    reader!(
        "validator/src/inventory/legacy/scope.rs",
        "legacy/scope.rs",
        false
    ),
    reader!(
        "validator/src/inventory/plugin_manifest_hooks/mod.rs",
        "plugin_manifest_hooks/mod.rs",
        false
    ),
    reader!(
        "validator/src/inventory/agent/manifest_digests.rs",
        "agent_reader_guard_manifest_digests.rs",
        false
    ),
    reader!(
        "validator/src/inventory/validate/mod.rs",
        "validate/mod.rs",
        false
    ),
    reader!("validator/src/lib.rs", "../lib.rs", false),
    reader!("validator/src/package/mod.rs", "../package/mod.rs", false),
    reader!(
        "validator/src/review/materiality/mod.rs",
        "../review/materiality/mod.rs",
        false
    ),
    reader!(
        "validator/src/review/materiality/registry.rs",
        "../review/materiality/registry.rs",
        false
    ),
    reader!(
        "validator/src/review/round/report.rs",
        "../review/round/report.rs",
        false
    ),
    reader!(
        "validator/src/schema_catalog/fixture_schema_rules.rs",
        "../schema_catalog/fixture_schema_rules.rs",
        true
    ),
    reader!(
        "validator/src/schema_catalog/mod.rs",
        "../schema_catalog/mod.rs",
        false
    ),
    reader!(
        "validator/src/schema_catalog/schema/patterns.rs",
        "../schema_catalog/schema/patterns.rs",
        true
    ),
];
