use serde_json::json;

#[test]
fn target_repo_safe_fs_rejects_escape_symlink_directory_and_bad_utf8_boundaries() {
    let root = crate::self_tests::boundaries::support::temp_root("target-safe-fs");
    std::fs::create_dir_all(root.join("dir")).expect("dir");
    std::fs::write(root.join("file.txt"), "ok").expect("file");
    std::fs::write(root.join("bad.bin"), [0xff, 0xfe]).expect("bad utf8");
    assert!(crate::target_repo::safe_fs::is_regular_file(
        &root, "file.txt"
    ));
    assert!(crate::target_repo::safe_fs::is_nonempty_file(
        &root, "file.txt"
    ));
    assert!(crate::target_repo::safe_fs::is_dir(&root, "dir"));
    assert!(!crate::target_repo::safe_fs::is_regular_file(&root, "dir"));
    assert!(!crate::target_repo::safe_fs::is_dir(&root, "file.txt"));
    assert!(crate::target_repo::safe_fs::regular_path(&root, "../escape").is_err());
    assert!(crate::target_repo::safe_fs::read_to_string(&root, "bad.bin").is_err());
    #[cfg(unix)]
    {
        std::os::unix::fs::symlink("file.txt", root.join("link.txt")).expect("symlink");
        assert!(crate::target_repo::safe_fs::regular_path(&root, "link.txt").is_err());
    }
    std::fs::remove_dir_all(root).expect("cleanup safe fs");
}

#[test]
fn target_repo_receipt_gate_and_runtime_legibility_edges_fail_closed() {
    let root = crate::self_tests::boundaries::support::temp_root("target-repo-gate-runtime");
    std::fs::create_dir_all(root.join("docs")).expect("docs");
    std::fs::write(root.join("Cargo.toml"), "[package]\nname=\"demo\"\n").expect("cargo");
    std::fs::write(root.join("docs/runtime.md"), "runtime receipt").expect("runtime");

    let (receipt, _code) = crate::target_repo::audit_target_repo(
        &root,
        "fresh-init",
        "target audit",
        &[],
        false,
        false,
        None,
    );
    assert_eq!(
        receipt["checks"]["runtime-legibility"]["status"], "pass",
        "{receipt}"
    );

    let malformed_gate = json!({
        "repo_fingerprint":"wrong",
        "checks":{"check-gate":{"status":"pass"}},
        "gate_markers":["baseline-files"]
    });
    let errors = crate::target_repo::target_receipt_errors(&malformed_gate);
    assert!(
        errors
            .iter()
            .any(|err| err == "target gate missing required markers")
    );
    assert!(
        errors
            .iter()
            .any(|err| err == "target gate missing stdout/stderr digests")
    );
    assert!(
        errors
            .iter()
            .any(|err| err == "target repo fingerprint mismatch")
    );

    assert!(!crate::target_repo::worktree_env_contract::text_ok(
        "[cleanup]\n"
    ));
    assert!(!crate::target_repo::worktree_env_contract::text_ok(
        "[setup]\n"
    ));
    let actions = r#"
[[actions]]
name = "Fast Check"
script = "source .codex-worktree/env.sh || { echo scripts/check is required for Fast Check; exit 2; }"
[[actions]]
name = "Other"
script = "true"
[[actions]]
name = "Another"
script = "true"
"#;
    let header = "# THIS IS AUTOGENERATED. DO NOT EDIT MANUALLY\nversion = 1\nname = \"demo\"\n";
    let setup = r#"
[setup]
script = "CODEX_WORKTREE_PATH=${CODEX_WORKTREE_PATH:-$PWD}; $HOME/.codex/bin/codex-worktree-env"
"#;
    let cleanup = r#"
[cleanup]
script = "CODEX_WORKTREE_PATH=${CODEX_WORKTREE_PATH:-$PWD}; cleanup_receipt=cleanup.json; find .codex-worktree -type f | sort; rm -rf .codex-worktree"
"#;
    assert!(!crate::target_repo::worktree_env_contract::text_ok(
        &format!("{header}{cleanup}{actions}")
    ));
    assert!(!crate::target_repo::worktree_env_contract::text_ok(
        &format!("{header}{setup}{actions}")
    ));
    std::fs::remove_dir_all(root).expect("cleanup target repo gate runtime");
}
