pub(crate) const REQUIRED_COMMANDS: &[&str] = &[
    "package digest",
    "source audit",
    "red fixture report",
    "schema validation",
    "mandatory-law validation",
    "standards-gardener rebind",
    "source-obligations check",
    "foundational-trace check",
    "coverage prove",
    "line-cap check",
    "namespace check",
    "product prove-fitness",
    "product prove-cohesion",
    "product prove-journey",
    "fit-repo prove",
    "review-round verify",
    "review-target build",
    "archive build",
    "final-packet prove",
    "registry probe",
    "install audit",
    "cache audit",
    "transaction finalize",
    "update-goal eligibility",
    "self update-goal eligibility",
    "rust toolchain verify",
    "rust fast",
    "rust standard",
    "rust release",
    "rust clean-proof",
    "rust watch",
    "rust memory prove",
    "rust dependency audit",
    "rust coverage prove",
    "rust workspace topology",
    "gc plan",
    "gc dry-run",
    "gc apply",
    "gc verify",
    "halo capability prove",
    "session-log hardening",
    "target-repo audit",
    "observe stack up",
    "observe stack health",
    "observe stack smoke",
    "observe stack down",
    "observe stack gc plan",
    "observe stack gc dry-run",
    "observe stack gc apply",
    "observe logs query",
    "observe metrics query",
    "observe traces query",
    "observe snapshot",
    "observe prove",
    "observe explain-failure",
    "observe explain-claim",
    "observe explain-check",
    "observe explain-law",
    "openai call prove",
    "openai config prove",
    "openai output prove",
    "promptfoo prove",
    "current-state",
    "improvement-loop prove",
    "loop format check",
    "loop measure",
    "loop run",
    "observe command-roundtrip",
    "observe explain --next",
    "package inventory",
    "performance prove",
    "routine check",
    "typed-boundaries check",
];
