use serde::Serialize;

pub(crate) const REQUIRED_COMMANDS: &[&str] = &[
    "ultragoal audit",
    "ultragoal package digest",
    "ultragoal review-target build",
    "ultragoal archive build",
    "ultragoal review-round verify",
    "ultragoal law graph --strict",
    "ultragoal law check --gate <gate-id>",
    "ultragoal law check --all",
    "ultragoal standards check --strict",
    "ultragoal source-obligations check --strict",
    "ultragoal foundational-trace check --strict",
    "ultragoal namespace check --strict",
    "ultragoal typed-boundaries check --strict",
    "ultragoal line-caps check --strict",
    "ultragoal coverage prove",
    "ultragoal performance prove",
    "ultragoal performance verify",
    "ultragoal performance budgets",
    "ultragoal product init",
    "ultragoal product prove-fitness",
    "ultragoal product prove-cohesion",
    "ultragoal product prove-success",
    "ultragoal product check-claims",
    "ultragoal capability discover",
    "ultragoal capability prove",
    "ultragoal install audit",
    "ultragoal cache audit",
    "ultragoal registry probe",
    "ultragoal app-surface probe",
    "ultragoal target-repo audit",
    "ultragoal package inventory",
    "ultragoal package verify",
    "ultragoal packet build",
    "ultragoal packet verify",
    "ultragoal receipts verify",
    "ultragoal fixtures red",
    "ultragoal fixtures green",
    "ultragoal fixtures tamper",
    "ultragoal fixtures all",
    "ultragoal clean-room rebuild",
    "ultragoal claim-ceiling compute",
    "ultragoal explain <failure-id>",
    "ultragoal failure capture",
    "ultragoal failure promote",
    "ultragoal issue check-lifecycle",
    "ultragoal transaction finalize",
    "ultragoal update-goal eligibility",
    "ultragoal self audit --strict",
    "ultragoal self law-graph --strict",
    "ultragoal self fixtures red",
    "ultragoal self fixtures green",
    "ultragoal self fixtures tamper",
    "ultragoal self performance prove",
    "ultragoal self update-goal eligibility",
];

#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub(crate) enum ControlOperation {
    LawGraphStrict,
    LawCheckGate,
    LawCheckAll,
    StandardsCheckStrict,
    SourceObligationsCheckStrict,
    FoundationalTraceCheckStrict,
    NamespaceCheckStrict,
    TypedBoundariesCheckStrict,
    LineCapsCheckStrict,
    CoverageProve,
    ProductInit,
    ProductProveFitness,
    ProductProveCohesion,
    ProductProveSuccess,
    ProductCheckClaims,
    CapabilityDiscover,
    CapabilityProve,
    InstallAudit,
    CacheAudit,
    RegistryProbe,
    AppSurfaceProbe,
    TargetRepoAudit,
    PackageInventory,
    PackageVerify,
    PacketBuild,
    PacketVerify,
    ReceiptsVerify,
    FixturesRed,
    FixturesGreen,
    FixturesTamper,
    FixturesAll,
    CleanRoomRebuild,
    ClaimCeilingCompute,
    Explain,
    FailureCapture,
    FailurePromote,
    IssueCheckLifecycle,
    UpdateGoalEligibility,
    SelfAuditStrict,
    SelfLawGraphStrict,
    SelfFixturesRed,
    SelfFixturesGreen,
    SelfFixturesTamper,
    SelfUpdateGoalEligibility,
}

impl ControlOperation {
    pub(crate) fn id(self) -> &'static str {
        match self {
            Self::LawGraphStrict => "law_graph_strict",
            Self::LawCheckGate => "law_check_gate",
            Self::LawCheckAll => "law_check_all",
            Self::StandardsCheckStrict => "standards_check_strict",
            Self::SourceObligationsCheckStrict => "source_obligations_check_strict",
            Self::FoundationalTraceCheckStrict => "foundational_trace_check_strict",
            Self::NamespaceCheckStrict => "namespace_check_strict",
            Self::TypedBoundariesCheckStrict => "typed_boundaries_check_strict",
            Self::LineCapsCheckStrict => "line_caps_check_strict",
            Self::CoverageProve => "coverage_prove",
            Self::ProductInit => "product_init",
            Self::ProductProveFitness => "product_prove_fitness",
            Self::ProductProveCohesion => "product_prove_cohesion",
            Self::ProductProveSuccess => "product_prove_success",
            Self::ProductCheckClaims => "product_check_claims",
            Self::CapabilityDiscover => "capability_discover",
            Self::CapabilityProve => "capability_prove",
            Self::InstallAudit => "install_audit",
            Self::CacheAudit => "cache_audit",
            Self::RegistryProbe => "registry_probe",
            Self::AppSurfaceProbe => "app_surface_probe",
            Self::TargetRepoAudit => "target_repo_audit",
            Self::PackageInventory => "package_inventory",
            Self::PackageVerify => "package_verify",
            Self::PacketBuild => "packet_build",
            Self::PacketVerify => "packet_verify",
            Self::ReceiptsVerify => "receipts_verify",
            Self::FixturesRed => "fixtures_red",
            Self::FixturesGreen => "fixtures_green",
            Self::FixturesTamper => "fixtures_tamper",
            Self::FixturesAll => "fixtures_all",
            Self::CleanRoomRebuild => "clean_room_rebuild",
            Self::ClaimCeilingCompute => "claim_ceiling_compute",
            Self::Explain => "explain",
            Self::FailureCapture => "failure_capture",
            Self::FailurePromote => "failure_promote",
            Self::IssueCheckLifecycle => "issue_check_lifecycle",
            Self::UpdateGoalEligibility => "update_goal_eligibility",
            Self::SelfAuditStrict => "self_audit_strict",
            Self::SelfLawGraphStrict => "self_law_graph_strict",
            Self::SelfFixturesRed => "self_fixtures_red",
            Self::SelfFixturesGreen => "self_fixtures_green",
            Self::SelfFixturesTamper => "self_fixtures_tamper",
            Self::SelfUpdateGoalEligibility => "self_update_goal_eligibility",
        }
    }
}
